version: '3.9'
services:
  java_cont:
    build:
      context: ../
      dockerfile: docker/java/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "../../demo:/app"
  mysql_cont:
    build:
      context: ../docker
      dockerfile: mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
