version: '1.0'
services:
  java_cont:
    build:
      context: ../
      dockerfile: docker/java/Dockerfile
#    image: java_img
    ports:
      - "8080:8080"
    volumes:
      - "../../demo:/app"
#  mysql_cont:
#    build:
#      context: ../docker
#      dockerfile: mysql/Dockerfile
##    image: mysql_img:1.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "3306:3306"
